from typing import NoReturn
from .publication import Publication
from .subscription import Subscription


class Context:
    def __init__(self, aeron_dir: str=None, **kwargs) -> NoReturn: ...

    def __enter__(self) -> Context: ...
    def __exit__(self, exc_type, exc_val, exc_tb) -> NoReturn: ...

    def add_subscription(self, channel: str, stream_id: int) -> Subscription: ...
    def add_publication(self, channel: str, stream_id: int) -> Publication: ...